### ISSUE TITLE
Project specific settings being added to the SerialLoops menu rather than the file menu on Mac

### ISSUE THREAD

**Issue by jonko0493** [haroohie-club/SerialLoops#65]
Should be added to the file menu like New Project, etc.

Additionally, closing the program might make more sense in the SerialLoops menu, or just not being added at all on Mac since there's already a quit button there.

**Comment by WiIIiam278** [comment]
Caused by my oversight, actually, when I removed those elements from the File menu on the home page. Adding stuff to the menu is split in two methods, one for the base stuff in all areas, and another to add when you open a project. 
Caused by the fact that when adding to both a MenuBar's Items  and ApplicationItems, The Mac UI adds two child menus compared to just one with Wpf/Gtx, and the way I populate the rest of the menu bar items is by geting the first child menu in the submenu and adding to that, so it's adding to the wrong menu in mac
